name: Type Checking

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  mypy:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r paye_ton_kawa/requirements.txt
    - name: MyPy strict
      run: |
        mypy --strict --config-file=paye_ton_kawa/mypy.ini --exclude paye_ton_kawa/manage.py paye_ton_kawa/
